services:
  backend:
    build:
      context: ./backend-repo
      dockerfile: Dockerfile
    container_name: hierarchy-backend
    restart: unless-stopped
    environment:
      PORT: 4000
      MONGO_URI: mongodb+srv://chandel:chandels@cluster0.gizrixl.mongodb.net/hierarchy_wallet?retryWrites=true&w=majority
      JWT_SECRET: replace_with_long_secret
      JWT_EXPIRES_IN: 1d
      CLIENT_URL: http://localhost:4200
      SESSION_SECRET: replace_with_session_secret
      OWNER_DEFAULT_PASSWORD: Owner@123
      ADMIN_DEFAULT_PASSWORD: Admin@123
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend-repo
      dockerfile: Dockerfile
    container_name: hierarchy-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:80"